# 開発・テスト用：MySQL
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] || "localhost" %>
  socket: <%= ENV["MYSQL_SOCKET"] || "/tmp/mysql.sock" %>

development:
  <<: *default
  database: sorairo_note_development

test:
  <<: *default
  database: sorairo_note_test

# 本番用：PostgreSQL（Render）
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>
  variables:
    sslmode: <%= ENV.fetch("PGSSLMODE", "require") %>
