# 開発・テスト用：MySQL
default_mysql: &default_mysql
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] || "localhost" %>
  socket: /tmp/mysql.sock

development:
  <<: *default_mysql
  database: sorairo_note_development

test:
  <<: *default_mysql
  database: sorairo_note_test

# 本番用：PostgreSQL（Render）
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
  sslmode: require
