# 開発・テスト用：MySQL
default_mysql: &default_mysql
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] || "localhost" %>
  socket: /tmp/mysql.sock

development:
  <<: *default_mysql
  database: sorairo_note_development

test:
  <<: *default_mysql
  database: sorairo_note_test

# 本番用：PostgreSQL（Render）
default_postgresql: &default_postgresql
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] || 5432 %>

production:
  <<: *default_postgresql
  database: <%= ENV["DB_NAME"] %>
