default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: root
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] || "localhost" %>
  # socket: （必要に応じて指定）

development:
  <<: *default
  database: sorairo_note_development

test:
  <<: *default
  database: sorairo_note_test

production:
  <<: *default
  database: sorairo_note_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  # socket: （必要に応じて指定）