default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] || "localhost" %>
  # socketはローカル環境のMySQLにソケット接続する場合に指定（不要ならコメントアウト）
  socket: <%= ENV["MYSQL_SOCKET"] if ENV["MYSQL_SOCKET"].present? %>

development:
  <<: *default
  database: sorairo_note_development

test:
  <<: *default
  database: sorairo_note_test

production:
  <<: *default
  database: sorairo_note_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  socket: <%= ENV["DB_SOCKET"] if ENV["DB_SOCKET"].present? %>
